added step with docker compose instalation

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,6 +25,16 @@ jobs:
           java-version: '17'
           cache: 'maven'
 
+      - name: Check Docker Compose Version
+        run: docker-compose --version || echo "Docker Compose not found"
+
+      - name: Install Docker Compose (if missing)
+        run: |
+          if ! command -v docker-compose &> /dev/null; then
+            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+          fi
+
       # Step 3: Start Selenium Grid (Docker Compose)
       - name: Start Selenium Grid
         run: docker-compose up -d
